# -*- coding: utf-8 -*-
"""Mall_Customers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHBN3lH6T6vI3tUO9o28yQI9EuGC6G9h
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

from google.colab import files
files.upload()

customer_data =pd.read_csv('Mall_Customers.csv')

customer_data.head()

customer_data.shape

customer_data.info()

customer_data.describe()

customer_data.isnull().sum()

"""**Choosing the Annual Income column and spending column**"""

x=customer_data.iloc[:,[3,4]].values

print(x)

"""Choosing the number of clusters


WCSS - Within cluster sum of square **bold text**
"""

wcss=[]

for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(x)


  wcss.append(kmeans.inertia_)

sns.set()
plt.plot(range(1,11),wcss)
plt.title('The elbow method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

"""**Training the K-means clustering model**"""

kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)
Y=kmeans.fit_predict(x)

print(Y)

"""Clusters - 0,1,2,3,4

**Visualizing all the clusters**
"""

plt.figure(figsize=(8,8))
plt.scatter(x[Y==0,0,],x[Y==0,1],s=50,c='green',label='Cluster 1')
plt.scatter(x[Y==1,0,],x[Y==1,1],s=50,c='red',label='Cluster 2')
plt.scatter(x[Y==2,0,],x[Y==2,1],s=50,c='purple',label='Cluster 3')
plt.scatter(x[Y==3,0,],x[Y==3,1],s=50,c='black',label='Cluster 4')
plt.scatter(x[Y==4,0,],x[Y==4,1],s=50,c='blue',label='Cluster 5')

plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=100,c='cyan',label='Centroids')
plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()